Making Uri proto, microuri support mandatory and longuri support optional
eclipse-uprotocol/up-spec pull request #110
Opened 2024-04-09 16:42 UTC by ruchirchauhan

This PR implements issue #102 

It modifies uri.proto:

1. UEntity name is now optional
2. UEntity id is now required
3. UResource name is now optional
4. UResource id is now required

2024-04-09 16:59 UTC, stevenhartley requested changes
The purpose of this change is to allow us to build URIs that contain only numbers that could be used for micro and short URI format however if we put id as mandatory and name optional, we will not be able to build URIs that are in long format only (meaning URIs that only contain names). Since UUri is a container to store the URI information, it needs to support the ability to contain in its belly:

1. Names only
2. Numbers only
3. Names & numbers

The changes I've proposed allows the UUri to contain any of the above information, please consider the suggestions

2024-04-09 16:59 UTC, stevenhartley commented on up-core-api/uprotocol/uri.proto
> +  uint32 id = 2;                     // The numeric ID for the uEntity assigned from the name/number registry
```suggestion
  optional uint32 id = 2;                     // The numeric ID for the uEntity assigned from the name/number registry
```

2024-04-09 16:59 UTC, stevenhartley commented on up-core-api/uprotocol/uri.proto
> +  uint32 id = 4;                 // Numerical representation of the UResource portion of the UUri
```suggestion
  optional uint32 id = 4;                 // Numerical representation of the UResource portion of the UUri
```

2024-04-09 18:21 UTC, ruchirchauhan commented on up-core-api/uprotocol/uri.proto
> +  uint32 id = 2;                     // The numeric ID for the uEntity assigned from the name/number registry
Done

2024-04-09 19:05 UTC, stevenhartley approved these changes
Approved

2024-04-09 19:07 UTC, merged

2024-04-10 11:41 UTC, sophokles73 commented
@stevenhartley it would be nice if we could squash PRs like this before merging in the future to keep the commit log in a clean and consistent state. We now have three commits in the log, each of which represents intermediate work and which only make sense when applied together ...