Remove ambiguity around uAttributes requirements
eclipse-uprotocol/up-spec pull request #111
Opened 2024-04-10 07:35 UTC by sophokles73

Addresses #71

The requirements regarding the usage of particular UAttributes
properties for the message types supported by uProtocol had been
scattered around multiple documents, some textual descriptions as well
as proto files. It was hard to find the relevant information and to
keep it consistent across the specifications.

The following things have been done to mitigate the situation:
* The uattributes.adoc file is now the single source of truth regarding
  the usage of UAttributes for the supported message types. All
  corresponding definitions have been removed from the cloudevents.adoc
  and uattributes.proto files.
* The cloudevents.adoc file has been moved to the up-l1 folder because
  its content is relevant to uProtocol Client libraries only that use
  CloudEvents' JSON or Protobuf Format to map UMessages to a transport
  protocol's PDU. Application (uEntity) developers will not get in
  touch with CloudEvents at all.

2024-04-10 20:29 UTC, PLeVasseur approved these changes
Wow @sophokles73, this is great!

Looking forward to your `UUri` cleanup next :slightly_smiling_face:

2024-04-10 22:05 UTC, stevenhartley requested changes
Very minor changes but thankyou so much @sophokles73 !!

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to the value of the `uprotocol.ce_name` option defined for the
```suggestion
* *MUST* be set to the value of the `uprotocol.ce_name` option defined for the
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
```suggestion
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to either the long or short form link:uri.adoc[serialization of the URI]
```suggestion
* *MUST* be set to either the long or short form link:uri.adoc[serialization of the URI]
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to either the long or short form link:uri.adoc[serialization of the URI]
```suggestion
* *MUST* be set to either the long or short form link:uri.adoc[serialization of the URI]
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to the value of the `uprotocol.ce_name` option defined for the
```suggestion
* *MUST* be set to the value of the `uprotocol.ce_name` option defined for the
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +a|The amount of time (in milliseconds) after which this message MUST no longer be delivered/processed.
```suggestion
a|The amount of time (in milliseconds) after which this message *MUST* no longer be delivered/processed.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
```suggestion
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +* MUST be set to the link:../up-core-api/uprotocol/ustatus.proto[UCode]'s integer value
```suggestion
* *MUST* be set to the link:../up-core-api/uprotocol/ustatus.proto[UCode]'s integer value
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +The rules defined in https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/protobuf-format.md[Protobuf Event Format for CloudEvents, Version 1.0.2] MUST be applied when mapping UPayload
```suggestion
The rules defined in https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/protobuf-format.md[Protobuf Event Format for CloudEvents, Version 1.0.2] *MUST* be applied when mapping UPayload to CloudEvents using the Protobuf Format. The table below defines specific values to use for the different UMessage payload types.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +This mapping MUST be used by link:../upclient.adoc[uProtocol Client Libraries] which use the Protobuf Event Format for the binding to a particular transport protocol.
```suggestion
This mapping *MUST* be used by link:../upclient.adoc[uProtocol Client Libraries] which use the Protobuf Event Format for the binding to a particular transport protocol.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +The rules defined in https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md[JSON Event Format for CloudEvents, Version 1.0.2] MUST be applied when mapping UPayload to Clou
```suggestion
The rules defined in https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md[JSON Event Format for CloudEvents, Version 1.0.2] *MUST* be applied when mapping UPayload to CloudEvents using the JSON Format. The table below defines specific values to use for the different UMessage payload types.
```

2024-04-10 22:05 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +This mapping MUST be used by link:../upclient.adoc[uProtocol Client Libraries] which use the JSON Event Format for the binding to a particular transport protocol.
```suggestion
This mapping *MUST* be used by link:../upclient.adoc[uProtocol Client Libraries] which use the JSON Event Format for the binding to a particular transport protocol.
```

2024-04-11 09:05 UTC, sophokles73 commented on basics/cloudevents.adoc
Good point, I think that should be doable.

2024-04-11 09:31 UTC, sophokles73 commented
@stevenhartley I have fixed the formatting and used `git mv` to move the cloudevents stuff. Can you check if this did the trick for you? I can then squash and merge ...

2024-04-11 09:37 UTC, sophokles73 commented on up-l1/cloudevents.adoc
> +SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
I do not see why it shouldn't. I wanted to remove the duplication of the copyright info. Do you have any particular concerns?

2024-04-11 13:31 UTC, stevenhartley commented on up-l1/cloudevents.adoc
> +SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
nope, it is fine

2024-04-11 13:35 UTC, stevenhartley commented
> the cloudevents stuff. Can you check if this di

Didn't seem to work (git mv) but that is fine, I'll just look at the history if needed

2024-04-11 13:36 UTC, stevenhartley approved these changes

2024-04-11 15:08 UTC, merged