Merge up-spec and up-core-api
eclipse-uprotocol/up-spec pull request #91
Opened 2024-03-18 17:30 UTC by stevenhartley

the following change takes the 1.5.7 release of up-core-api and merges it with up-spec so we can have better traceability with the spec and protos.

#88

2024-03-26 01:17 UTC, stevenhartley commented
@sophokles73 any objections to merge this PR and freeze the core-api project?

2024-03-26 19:13 UTC, PLeVasseur approved these changes
LGTM aside from the one thing I found which still pointed to `up-core-api`

2024-03-28 00:20 UTC, stevenhartley commented on up-core-api/uprotocol/uattributes.proto
> +    // A https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/ustatus.proto[code] indicating an error that has occurred
Done

2024-03-28 17:17 UTC, sophokles73 requested changes

2024-03-28 17:17 UTC, sophokles73 commented on basics/upayload.adoc
> +NOTE: Please refer tolink:../../up-core-api/uprotocol/upayload.proto[upayload.proto] for more details
missing whitespace

2024-03-28 17:17 UTC, sophokles73 commented on up-l3/usubscription/v3/README.adoc
> +NOTE: uSubscription interface is definedlink:../../../up-core-api/uprotocol/core/usubscription/v3/usubscription.proto[usubscription.proto] and follows link:../../../basics/error_model.adoc[uProtocol
missing whitespace

2024-03-28 20:17 UTC, stevenhartley commented on basics/upayload.adoc
> +NOTE: Please refer tolink:../../up-core-api/uprotocol/upayload.proto[upayload.proto] for more details
fixed

2024-03-28 20:19 UTC, stevenhartley commented on up-l3/usubscription/v3/README.adoc
> +NOTE: uSubscription interface is definedlink:../../../up-core-api/uprotocol/core/usubscription/v3/usubscription.proto[usubscription.proto] and follows link:../../../basics/error_model.adoc[uProtocol
fixed

2024-04-02 13:25 UTC, sophokles73 approved these changes
LGTM

2024-04-02 17:04 UTC, merged